name: Process YAML Files

on:
  schedule:
    - cron: '0 12 * * *'  # 每天中午12点执行

jobs:
  process_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Unbreak-classical.yaml
      run: |
        curl -s https://raw.githubusercontent.com/qoli/SyncnextClash/main/Unbreak-classical.yaml -o Unbreak-classical.yaml

    - name: Process Unbreak-classical.yaml
      run: |
        sed '1d' Unbreak-classical.yaml | sed 's/  - //' > Unbreak-classical.list

    - name: Download proxy-classical.yaml
      run: |
        curl -s https://raw.githubusercontent.com/qoli/SyncnextClash/main/proxy-classical.yaml -o proxy-classical.yaml

    - name: Process proxy-classical.yaml
      run: |
        sed '1d' proxy-classical.yaml | sed 's/  - //' > proxy-classical.list

    - name: Commit and push files
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add Unbreak-classical.list proxy-classical.list
        git commit -m "Update Unbreak-classical.list and proxy-classical.list"
        git push

      # Optional: Use the `GITHUB_TOKEN` for authentication (default token provided by GitHub Actions)
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
